#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: func

# STEP: vivado_flow
cd /home/shadab/RTL_to_GDS/lab
vivado -mode batch -nojournal -nolog -source /home/shadab/RTL_to_GDS/lab/HLS_output//Synthesis/vivado_flow/vivado.tcl


