#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: add

# STEP: vivado_flow
cd /home/shadab/RTL_to_GDS/lab_3/Adder
vivado -mode batch -nojournal -nolog -source /home/shadab/RTL_to_GDS/lab_3/Adder/HLS_output//Synthesis/vivado_flow/vivado.tcl


